### ISSUE TITLE
how to convert date to persian date?

### ISSUE THREAD

**Issue by hnadi14** [samanzamani/PersianDate#1]
How to use parseGrg(String date,String pattern) ?

**Comment by samanzamani** [comment]
According to date format use `YYYY` for year like 2017,`MM` for month (05),`dd` for day(21), `HH` for hour(13), `mm` for minute (56) and `ss` for second (23).
For example for convert `2017-05-12 12:20:00` from String to `PersianDate` object use below code:
```
PersianDateFormat pdFormat = new PersianDateFormat();
try{
    PersianDate pdate = pdFormat.parseGrg("2017-05-12 12:20:00","YYYY-MM-dd HH:mm:ss"
}catch(ParseException e){
    log.e("LOG","String not match with format");
}
```);

**Comment by reza-khalafi** [comment]
How to get Persian date with custom format like this? 
PersianDateFormat pdFormat = new PersianDateFormat("F y j");
I tried some of formats but they did not work.
