### ISSUE TITLE
no AM_PM specifier in pattern items

### ISSUE THREAD

**Issue by ali73** [samanzamani/PersianDate#10]
It would be great if you had put a pattern item for parsing am/pm .
Thanks for your great library.

**Comment by samanzamani** [comment]
From version `0.4` You can use `a` and `A` for format `ق.ظ|ب.ظ` and `قبل از ظهر|بعد از ظهر`.
sample:
```java
PersianDate pdate = New PersianDate();
PersianDateFormat.format(pdate,"H:i a");//return 11:58 ق.ظ
PersianDateFormat.format(pdate,"H:i A");//return 11:58 قبل از ظهر
```
