### ISSUE TITLE
parse persian date string error

### ISSUE THREAD

**Issue by fofaraz** [samanzamani/PersianDate#12]
Hi
is there something wrong here:

PersianDateFormat format = new PersianDateFormat();
format.parse("1397-08-31","YYYY-MM-dd")

I'm getting this error:
Method threw 'java.lang.StringIndexOutOfBoundsException' exception. Cannot evaluate saman.zamani.persiandate.PersianDate.toString()

help me please

**Comment by samanzamani** [comment]
you must use `yyyy` instead of `YYYY`.

```java
PersianDateFormat format = new PersianDateFormat();
format.parse("1397-08-31","yyyy-MM-dd");
```

**Comment by fofaraz** [comment]
thanks 
i will try that
please fix this in documentation

![image](https://user-images.githubusercontent.com/18643641/44943275-c980c200-add8-11e8-9af0-4c429306e98f.png)

**Comment by samanzamani** [comment]
Readme file modified.
Thank you for your report.
