### ISSUE TITLE
تبدیل تاریخ میلادی به شمسی

### ISSUE THREAD

**Issue by mhkhajehpoor** [samanzamani/PersianDate#13]
سلام. برای تبدیل تاریخ شمسی به میلادی 
`   persianDate=new PersianDate();
                   persianDate.toJalali(yearInt,monthInt,dayInt);
 Toast.makeText(getApplicationContext(),persianDate+"",Toast.LENGTH_SHORT).show();`
از کد بالا استفاده کردم ولی تاریخ امروز رو برمیگردونه

**Comment by samanzamani** [comment]
سلام
خروجی این متد یک ارایه از نوع اعداد صحیح و کارش تبدیل تاریخ میلادی به شمسیه ولی خود شی رو تحت تاثیر قرار نمیده.
برای تبدیل تاریخ از میلادی به شمسی از نمونه کد زیر استفاده کنید.

```java
PersianDate pdate = new PersianDate().initGrgDate(yearInt,monthInt,datInt);
```

**Comment by mhkhajehpoor** [comment]
ممنون ، اوکی شد
