### ISSUE TITLE
تبدیل تاریخ شمسی به میلادی 

### ISSUE THREAD

**Issue by mhkhajehpoor** [samanzamani/PersianDate#14]
سلام و وقت بخیر 
چطوری میتونم تاریخ شمسی رو به میلادی تبدیل کنم ؟
PersianDate pdate = new PersianDate().initGrgDate(yearInt,monthInt,datInt);
Log.i("LOG",pdate.toString());

از این فرمت استفاده کردم ولی فقط 
 initGrgDate
داره ، که برای تبدیل میلادی به شمسی هست 
ممنون

**Comment by samanzamani** [comment]
سلام
مشابه تاریخ میلادی می‌تونید از متد زیر استفاده کنید.
`initJalaliDate`

```java
PersianDate pdate = new PersianDate().initJalaliDate(yearInt,monthInt,datInt);
Log.i("LOG",pdate.toString());
```

**Comment by mhkhajehpoor** [comment]
سلام من از این متد قبلا استفاده کردم ولی به میلادی تبدیل نمیکنه 
initJalaliDate

تاریخ ورودی :
1370/09/30
و خروجیش به این شکل میشه 
![image](https://user-images.githubusercontent.com/38702413/46247664-994e3280-c41b-11e8-9d96-3544d0ec8db9.png)

**Comment by samanzamani** [comment]
تاریخ درست تبدیل میشه شما در نمایش اشتباه می‌کنید.
برای نمایش تاریخ به صورت میلادی از کلاس زیر استفاده کنید:
`PersianDateFormat`
[مشاهده مستندات](https://github.com/samanzamani/PersianDate#persiandateformat)

اگه فقط سال یا ماه میلادی می‌خوایید می‌تونید از متد‌های زیر هم استفاده کنید:
```java
pdate.getGrgYear();
pdate.getGrgMonth();
pdate.getGrgDay();
```

**Comment by mhkhajehpoor** [comment]
> 
> 
> تاریخ درست تبدیل میشه شما در نمایش اشتباه می‌کنید.
> برای نمایش تاریخ به صورت میلادی از کلاس زیر استفاده کنید:
> `PersianDateFormat`
> [مشاهده مستندات](https://github.com/samanzamani/PersianDate#persiandateformat)
> 
> اگه فقط سال یا ماه میلادی می‌خوایید می‌تونید از متد‌های زیر هم استفاده کنید:
> 
> ```java
> pdate.getGrgYear();
> pdate.getGrgMonth();
> pdate.getGrgDay();
> ```

**Comment by mhkhajehpoor** [comment]
تشکر

**Comment by mohsen202** [comment]
سپاس
