### ISSUE TITLE
make allowBackup=false

### ISSUE THREAD

**Issue by saliga** [samanzamani/PersianDate#15]
hey thank you for library
but you need to make allow Backup in your manifest file to false . because if i wanted to disable backup in my manifest ,it conflicts with yours. now i have to download your whole repository and import it manually.
peace <3

**Comment by samanzamani** [comment]
Hello
you can fix this with add below line in `manifest`. I will fix this in next version.
`tools:replace="allowBackup"`

**Comment by hossein75rn** [comment]
سلام خیلی عالی موفق باشی داداش گل

**Comment by samanzamani** [comment]
Problem solved in version 0.5.
