### ISSUE TITLE
`PersianDate(Long timeInSecond)` should be fed time in miliseconds not seconds

### ISSUE THREAD

**Issue by 2hamed** [samanzamani/PersianDate#2]
Hey there,
I just tested this out. Using `PersianDate(Long timeInSecond)` when supplied with time in seconds doesn't work properly while supplying time in miliseconds is the right way.

**Comment by samanzamani** [comment]
Hi
Thank you for your report. actually this variable get millisecond And I'm wrong in naming. The next update will be corrected.

**Comment by samanzamani** [comment]
Fixed in version 0.2.
