### ISSUE TITLE
مشکل در تاربع addDate

### ISSUE THREAD

**Issue by designer001** [samanzamani/PersianDate#20]
سلام
من با تابع
addDay 
کار می کردم که متوجه شدم درست کار نمی کنه.  کد شما رو بررسی کردم رسیدم به تابع
addDate
این تابع سال و ماه و روز و ساعت و دقیقه و ثانیه رو می گیره و با ضرب و تقسیم به تاریخ اضافه می کنه
در صورتی که سال همیشه 365 روز نیست و ماه هم همیشه 30 روز نیست. شما از این اعداد برای ضرب و جمع استفاده کردید.
به نظرم شما باید تاریخ فعلی میلادی رو بدست بیارید. و بعد با توابع خود جاوا تاریخ رو اضافه کنید و بعد از اون تبدیل به شمسی کنید
یه موردی هم که برخوردم تبدیل تاریخ شمسی(سال و ماه و ...) به تاریخ میلادی رو ندیدم
یا شاید هم متوجه نشدم

**Comment by samanzamani** [comment]
سلام
ممنون از گزارشتون.
با توجه به تغییرات عمده‌ای که در روش محاسبه در آپدیت نسخه ۰.۵ وجود داشت بعضی تابع‌ها ممکن درست کار نکنن.
این موردی که گفتید رو تست می‌کنم و در صورت نیاز اصلاح و نسخه جدید منتشر می‌کنم.

برای تبدیل تاریخ شمسی به میلادی از تابع زیر استفاده کنید.
```java
initJalaliDate()
```

**Comment by samanzamani** [comment]
ممنون از پیشنهادتون.
متد افزودن تاریخ بهینه سازی شد.
لطفا از نسخه ۰.۷ استفاده کنید.

**Comment by resistance1404** [comment]
سلام.وقت شما بخیر.ببخشید من نمیتونم برای تابع addMonth مقدار منفی بدم؟
یعنی می خوام مثلا از ما جاری یه ماه کم کنم بزنم addMonth(-1)
ممنون میشم کمک کنید
