### ISSUE TITLE
بدست آوردن ماه قبل و بعد

### ISSUE THREAD

**Issue by mahramane** [samanzamani/PersianDate#22]
سلام
چطور ماه قبل و ماه بعد از تاریخ فعلی را به دست بیارم؟

**Comment by samanzamani** [comment]
سلام
برای این کار متد‌های متفاوتی وجود دارد ولی ساده‌ترین روش گرفتن شماره ماه و اضافه و کم کردن یک ماه از آن می‌باشد.
نمونه کد:

```java
PersianDate pDate = new PersianDate();
int monthAfter = pDate.getShMonth();
		if(pDate.getShMonth() == 12)
			monthAfter = 1;
		else
			monthAfter++;
```

**Comment by mahramane** [comment]
ببخشید آقای زمانی من لازم دارم اگر ماه 12 بود تاریخ ماه یکم سال بعد رو برگشت بده
یه تابع خیلی خوب دارید توی کتابخونه تون به اسم addMonth(1) اما متاسفانه فقط میتونم ماه بعدرو باهاش به دست بیارم برای ماه قبل addMonth(-1) رو تست کردم کار نکرد ولی همین تابع توی Calendar به این شکله
Calendar cal = Calendar.getInstance();
cal.add(Calendar.MONTH, 1); برای ماه بعد
cal.add(Calendar.MONTH, -1); برای ماه قبل

**Comment by samanzamani** [comment]
برای ماه قبل تا این نسخه متدی ندارم ولی در نسخه بعد اضافه میشه.
یرای ماه بعد که از همین متد می‌تونید استفاده کنید . ولی برای ماه قبل باید خودتون چک کنید که با کم کردن یک ماه به سال قبل برمی‌گردید یا نه .
برای نمونه این کد شاید بتونه کمک‌تون بکنه
```java
PersianDate pDate = new PersianDate();
int monthAfter = pDate.getShMonth();
if(pDate.getShMonth() == PersianDate.FARVARDIN)
    pDate.setShMonth(12).setShYear(pDate.getShYear()-1)addDay(1);
else
    pDate.setShMonth(monthAfter-1)addDay(1);
```
با استفاده از این کد در نهایت تاریخی که بدست میارید روز اول ماه قبل و اگر سال هم تغییر کرده باشه اون هم اعمال خواهد شد

**Comment by mahramane** [comment]
ممنون از پاسخگوییتون 
منتظر آپدیت بعدیتون خواهم ماند انشالله تا یک ماه دیگه بتونید تکمیل کنید 
زنده باشید ♥
