### ISSUE TITLE
چرا مقدار دهی متغیر به صورت by reference انجام میشه؟

### ISSUE THREAD

**Issue by yosefghobadi20** [samanzamani/PersianDate#23]
PersianDate start_date=Date;
PersianDate end_date=Date.addMonth(1);
در مورد بالا به متغیر اول هم یک ماه اضافه میشه جرا؟

**Comment by samanzamani** [comment]
متد‌های که ادد دارند زمان مرجع ابجکت تاریخ رو تغییر می‌دن.
برای اینکه بتونید زمان قبل‌تر و بعد‌تر از یک تاریخ مشخص رو بگیرید باید یه ابجکت جدید ایجاد کنید.
نمونه کد:

```java
    PersianDate start_date = Date;
    PersianDate end_date = new PersianDate(Date.getTime()).addMonth(1);
```

**Comment by yosefghobadi20** [comment]
ممنونم دستت درد نکنه خیلی کتابخونه عالی هست
