### ISSUE TITLE
device datetime is returned not real time

### ISSUE THREAD

**Issue by AliEasy** [samanzamani/PersianDate#25]
Hi
PersianDate returns the device time and date
Is it the nature of your library or Im making a mistake in using ur library?!
if its normal would you please suggest a way to get the time and date in format 06:22:50 and 1398/05/06
Thanks:)

**Comment by samanzamani** [comment]
`PersianDate` object use `java.util.Date` for first-time initialize. Because of this `PersianDate` depend on device time.
**Format 1:**
```java
PersianDate pdate = new PersianDate();
PersianDateFormat pdformater = new PersianDateFormat('H:i:s');
pdformater.format(pdate);//return 06:22:50
```
**Format 2:**
```java
PersianDate pdate = new PersianDate();
PersianDateFormat pdformater = new PersianDateFormat('Y/m/d');
pdformater.format(pdate);//return 1398/05/06
```
