### ISSUE TITLE
بدست آوردن هفته در سال 

### ISSUE THREAD

**Issue by erfansajjadie** [samanzamani/PersianDate#26]
یک تابع برای بدست آوردن هفته گذشته از سال از روی تاریخ

**Comment by samanzamani** [comment]
تا نسخه ۰.۷ چنین تابعی وجود نداره. در آپدیت‌های بعدی اضافه میشه. تا اون موقع به راحتی می‌تونید با استفاده از روز در سال هفته در سال رو محاسبه کنید.

https://github.com/samanzamani/PersianDate/issues/24
