### ISSUE TITLE
Ability to change month names

### ISSUE THREAD

**Issue by NotNotMarshall** [samanzamani/PersianDate#28]
Hello there,
I wanted to ask if you could add the ability to have custom month names as you know that in Solar Hijri calendar months have different names in different Middle-Eastern regions and countries like in Afghanistan they use 2 different set of names in their 2 national languages of Dari (Farsi) and Pashto (Afghani) or in Kurdish its different.
You can refer to this article for more information:
https://en.wikipedia.org/wiki/Solar_Hijri_calendar#Details_of_the_modern_calendar

Thank you

**Comment by samanzamani** [comment]
Hi
Thank you for your suggestion to improve this library.
I will consider this in the next update.

**Comment by NotNotMarshall** [comment]
@samanzamani Hello, any news?
I am desperately waiting for this future to get your lib into my library. Please take it to consider. :(

**Comment by samanzamani** [comment]
Hi
Sorry for a long time since the last update
I hope to release a new version with this feature in next week

**Comment by samanzamani** [comment]
since version 0.8 you can `X`,`C` and `E` to display month name in `Afghan`, `Kurdish`, and `Pashto` in `PersianDateFormat`

**Comment by NotNotMarshall** [comment]
> since version 0.8 you can `X`,`C` and `E` to display month name in `Afghan`, `Kurdish`, and `Pashto` in `PersianDateFormat`

Thank you very much !!!! <3
