### ISSUE TITLE
Calculate Leap Year only by year

### ISSUE THREAD

**Issue by behiunforgiven** [samanzamani/PersianDate#3]
In some situations we need to know a year is leap or not only by Year.
`PersianDate.IsLeap(Year)`

Can you provide that?

**Comment by samanzamani** [comment]
In the next version I will consider this item.

**Comment by samanzamani** [comment]
Add two new static method in version 0.2:
```
PersianDate.isGrgLeap(int GrgYear)
PersianDate.isJalaliLeap(int ShYear)
```
