### ISSUE TITLE
wrong result in long past dates

### ISSUE THREAD

**Issue by sourena21** [samanzamani/PersianDate#30]
hi saman,
you have wrong calculation in some dates are more than 50 years past for example you converter give this result:  1311/11/9
for this date:  1933/01/30
but correct result is: 1311/11/10

it cause problem in calculating elderly peoples birthdate
thanx a lot

**Comment by samanzamani** [comment]
Hi
Thank you for your reporting :pray:
I'll check this

**Comment by meysam1717** [comment]
Hi saman,
I have this problem too,seems not fix this problem,i use version 0.8 in project

**Comment by samanzamani** [comment]
Hi @meysam1717 
A new version will be released soon.

**Comment by samanzamani** [comment]
Bug fixed in v1.0
