### ISSUE TITLE
محاسبه تاریخ

### ISSUE THREAD

**Issue by androidkade11** [samanzamani/PersianDate#31]
سلام 
ممنون از کمکتون
من دوتا تاریخ شمسی دارم که میخوام فاصله بینشون رو به روز بدست بیارم ولی متاسفانه نمیتونم ممنون میشم کمک کنید
مثال
1398/12/18
1398/12/20
== 2 روز

**Comment by androidkade11** [comment]
سلام مجدد
من تونستم با دستور زیر فاصله رو بدست بیارم 
ولی مشکلی که هست اینه که تا 99 روز اختلاف درست کار میکنه 
مثلا 
1398/12/18 - 1399/01/01 
رو به درستی 12 روز اعلام میکنه 
ولی برای 
1398/12/18 - 1500/01/01 
36 
روز اعلام میکنه 

اینم کدم:
                 startdatepersian.initJalaliDate(styear,stmonth,stday);
                 finishdatepersian.initJalaliDate(fiyear,fimonth,fiday);

                 long startDate = startdatepersian.getTime();
                 long finishDate = finishdatepersian.getTime();

                 long resultms = finishDate-startDate;

                 long days = (resultms / (60*60*24*1000)) % 365 ;

                result.setText(days+"روز");

**Comment by samanzamani** [comment]
سلام
برای محاسبه اختلاف ۲ تاریخ می تونید از ۲ متد زیر استفاده کنید:
‍‍‍‍‍```java
startdatepersian.initJalaliDate(styear,stmonth,stday);
finishdatepersian.initJalaliDate(fiyear,fimonth,fiday);
int day = startdatepersian. getDayuntilToday(finishdatepersian);//return diff days
int[] diff = startdatepersian. untilToday(finishdatepersian);//return diff days-months-years
```

**Comment by androidkade11** [comment]
یک دنیا ممنونم 
خیلی گلی 
کارم راه افتاد
