### ISSUE TITLE
wrong monthName

### ISSUE THREAD

**Issue by fziraki** [samanzamani/PersianDate#33]
سلام لطفاً این مورد رو چک کنید.

>         for (int i = 0 ; i < 12 ; i++){
> 
>             PersianDate persianDate = new PersianDate();
>             persianDate.setShYear(1399);
>             persianDate.setShMonth(i+1);
>             persianDate.setShDay(1);
> 
>             Log.d("TAG", "month name: "+persianDate.monthName());
>         }

امروز که 31 شهریور هست ماه مهر رو برنمی گردونه و اشتباهی بعد شهریور آبان رو برمیگردونه!

**Comment by samanzamani** [comment]
سلام
من همه جوره این مورد تست کردم مشکلی نبود
می تونید دقیق تر بگید چه مشکلی هست

**Comment by fziraki** [comment]
> سلام
> من همه جوره این مورد تست کردم مشکلی نبود
> می تونید دقیق تر بگید چه مشکلی هست

این مشکل فکر می کنم مربوط به ساعت و تایم زون باشه و فقط هم همون 31 شهریور بود یعنی فرداش درست شد!
فکر می کنم با جا به جایی ساعت مشکل پیدا می کنه
ازونجایی میگم که ساعت 12 شب که میشه هم روز نمیره به بعدی بعد چند ساعت اعمال میشه

**Comment by samanzamani** [comment]
اوکی
من مجدد تست می کنم

**Comment by samanzamani** [comment]
لطفا از نسخه ۱ استفاده کنید
