### ISSUE TITLE
مشکل در تاربع addMonth

### ISSUE THREAD

**Issue by resistance1404** [samanzamani/PersianDate#34]
سلام.وقت شما بخیر.ببخشید من نمیتونم برای تابع addMonth مقدار منفی بدم؟
یعنی می خوام مثلا از ما جاری یه ماه کم کنم بزنم addMonth(-1)
ممنون میشم کمک کنید

**Comment by samanzamani** [comment]
سلام
این سوال رو ببینید:
https://github.com/samanzamani/PersianDate/issues/22
