### ISSUE TITLE
End of month issue

### ISSUE THREAD

**Issue by fardinfrd** [samanzamani/PersianDate#36]
Hi Saman

Suppos current date is end of month, for example 30 Mehr 1399, when I call PersianDate constructor and set date to 1398/12/29 the result date has wrong result

```
PersianDate persianDate = new PersianDate(); // result is current date, such as 1399/07/30
persianDate.setShYear(1398); // 1398/07/30
persianDate.setShMonth(12); // 1398/12/30 -> 1399/01/01
persianDate.setShDay(29); // 1399/01/29
persianDate.getTime() // 1399/01/29 != 1398/12/29

```
It seems to need another constructor. (PersianDate(year, month, day))

thanks

**Comment by samanzamani** [comment]
Hi @fardinfrd 
I wa chacked methods but it worked currectly.
```java
		PersianDate persianDate = new PersianDate(); // result is current date, such as 1399/07/30
		persianDate.setShYear(1398)
				.setShMonth(12)
				.setShDay(29);
		Log.i("LOG","Date is" + PersianDateFormat.format(persianDate,null));
```
Although there is a method called `initJalaliDate` for initiation date with year, month, and day.
 Let me know if you have any problems.
