### ISSUE TITLE
monthName() method to display name in different dialects

### ISSUE THREAD

**Issue by NotNotMarshall** [samanzamani/PersianDate#38]
Salaam!
For the next release please add an optional parameter to monthName() method to return back names in different Persian dialects (Kurdi, Afghani, Irani).

What I am trying to achieve is:
`        return PersianDate(TimeUtils.getNowMills()).monthName()`

But for now it just returns it in Iranian name (e.g. Aazar).

Thanks a world!

**Comment by samanzamani** [comment]
Hi
Thank you for your contribution.
I will review and add this feature in the new version.

**Comment by samanzamani** [comment]
Add this feature in v1.0

**Comment by pooryadb** [comment]
hi
please make Dialect-enum **public** ,
currently it is package-private! and "public String **monthName**(int month, Dialect dialect)" isn't practical 

https://github.com/samanzamani/PersianDate/blob/ab8394f503b0c40532b3b29b237737ae1a568510/persiandate/src/main/java/saman/zamani/persiandate/PersianDate.java#L49

https://github.com/samanzamani/PersianDate/blob/ab8394f503b0c40532b3b29b237737ae1a568510/persiandate/src/main/java/saman/zamani/persiandate/PersianDate.java#L499

**Comment by pooryadb** [comment]
@samanzamani 
make new release, please

**Comment by samanzamani** [comment]
v1.3.3 released

**Comment by momeni1367** [comment]
سلام
Failed to resolve: com.github.samanzamani:PersianDate:1.3.4
 این خطا میده

ولی وقتی 
    releaseImplementation 'com.github.samanzamani:PersianDate:1.3.4'
میزارم رفع میشه خطا ولی 
val persianDate = PersianDate(date)
خطا میده تو 
 Jetpack

PersianDate نمیشناسه

**Comment by samanzamani** [comment]
سلام @momeni1367 
لطفا یک موضوع جدید برای این مسئله باز کنید تا بهم ریختگی ایجاد نشه.
ممنون
