### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by SdidevelopWork** [samanzamani/PersianDate#40]
**error when parsing**

string date =  "1399/09/07";
PersianDate persianDate = persianDateFormat.parse(date,"Y/m/d");

error message
java.lang.ArrayIndexOutOfBoundsException: length=13; index=-1

**Comment by samanzamani** [comment]
Hi
Look at https://github.com/samanzamani/PersianDate#persiandateformat in the documentation.
For parse, you must use YYYY for the year, MM for the month, and dd for the day.

```java
string date = "1399/09/07";
PersianDate persianDate = persianDateFormat.parse(date,"YYYY/MM/dd");
```

**Comment by SdidevelopWork** [comment]
hello,
thank you.
👍
