### ISSUE TITLE
Wrong date conversion in a specific date

### ISSUE THREAD

**Issue by MHKalantarian** [samanzamani/PersianDate#42]
Date converted to epoch
`1360/08/02 > 372780535866 UNIX`
But when I try to reverse this specific date using 
`new PersianDateFormat("Y/m/d").format(new PersianDate(372780535866 ))`
it returns `1360/07/01`

**Comment by MHKalantarian** [comment]
```

**Comment by samanzamani** [comment]
Bug fixed in v1.0
