### ISSUE TITLE
آپدیت

### ISSUE THREAD

**Issue by mahramane** [samanzamani/PersianDate#47]
سلام وقت بخیر
آیا امکانش هست نسخه جدید رو به زبان کاتلین منتشر کنید؟
زمان تقریبی رو هم بی زحمت میفرمایید
باتشکر

**Comment by samanzamani** [comment]
سلام
نسخه جدید هم هم جاوا خواهد بود
تا اخر اردیبهشت نسخه جدید منتشر خواهد شد
