### ISSUE TITLE
consider migrating to jitpack or maven central

### ISSUE THREAD

**Issue by yamin8000** [samanzamani/PersianDate#48]
@samanzamani
jCenter is currently deprecated and artifacts can only be downloaded till 2022-02-01, consider migrating to jitpack or maven central.
[more info here](https://developer.android.com/studio/build/jcenter-migration)

**Comment by samanzamani** [comment]
Hi
Thank you for your report
This change will be applied in the new version

**Comment by NotNotMarshall** [comment]
> @samanzamani
> jCenter is currently deprecated and artifacts can only be downloaded till 2022-02-01, consider migrating to jitpack or maven central.
> [more info here](https://developer.android.com/studio/build/jcenter-migration)

+1

**Comment by samanzamani** [comment]
Now you can get library from jitpack:

https://github.com/samanzamani/PersianDate#install
