### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by lrhm** [samanzamani/PersianDate#49]
- parsing and formatting in Persian numerals 

- subtractDate

for the first one, I'm suggesting to add "p" character before String and Pattern Keys i.e,  "'pYYYY-pMM-pdd" and "'py pj'". Another easier and lazier approach would be adding the argument `usePersianDialect` to `parse` and `format` functions and just replace Latin numerals to Persians before parsing and after formatting. I could implement this feature, since Kotlin first, i could also convert the project to Kotlin. 

the second one is as easy as the implemented adding day/month/year functionality, instead of adding to `timeInMilliSecond` we could subtract.

let me know what you think.

**Comment by samanzamani** [comment]
Hi
Thank you for your suggestion.
Since v0.9 is almost ready for release I will consider this feature for the first stable version v1.0.

**Comment by samanzamani** [comment]
Support Farsi character add in v1.3.3

https://github.com/samanzamani/PersianDate/issues/46
