### ISSUE TITLE
جابجا ثبت کردن بعضی تاریخ های خاص

### ISSUE THREAD

**Issue by sourena21** [samanzamani/PersianDate#51]
سلام
من موقع استفاده تو اپ متوجه شدم یه سری تاریخ های خاص که انتخاب کردیم رو اشتباه بر می گردونه تو لیستنر.
مثلا 12 بهمن 1398 رو 11 اسفند 1398 برمی گردونه
من زیاد تست نکردم که بفهمم به طور کلی مشکل چیه اما یه سری از این تاریخ ها رو اشتباه محاسبه می کنه

**Comment by samanzamani** [comment]
سلام
ممنون از گزارشتون
این مشکل به خاطر سال‌های کبیسه و مشکل در محاسباته که برطرف شده
در حال انتشار نسخه جدید هستم

**Comment by samanzamani** [comment]
https://github.com/samanzamani/PersianDate/issues/35
