### ISSUE TITLE
مشکل

### ISSUE THREAD

**Issue by mahramane** [samanzamani/PersianDate#54]
سلام

تابع getTime() ساعت و دقیقه و ثانیه و میلی  ثانیه توش نیست و به صورت پیشفرض 00:00:00:000 هست

`PersianDate().getTime();

**Comment by mahramane** [comment]
Change

```
  private void updateTimeStamp(){
    try {
      this.timeInMilliSecond = Objects.requireNonNull(new SimpleDateFormat("dd/MM/yyyy", this.locale)
          .parse("" + this.grgDay + "/" + this.grgMonth + "/" + this.getGrgYear())).getTime();
    } catch (ParseException e) {
      this.timeInMilliSecond = new Date().getTime();
    }
  }
```

to

```
    private void updateTimeStamp() {
        try {
            this.timeInMilliSecond = Objects.requireNonNull(new SimpleDateFormat("dd/MM/yyyy hh:mm:ss", this.locale)
                    .parse("" + this.grgDay + "/" + this.grgMonth + "/" + this.getGrgYear() + " " + this.hour + ":" + this.minute + ":" + this.second)).getTime();
        } catch (ParseException e) {
            this.timeInMilliSecond = new Date().getTime();
        }
    }
```

**Comment by samanzamani** [comment]
سلام
ممنون بابت گزارشتون 
بررسی می کنم

**Comment by mahramane** [comment]
> سلام
> ممنون بابت گزارشتون
> بررسی می کنم

در صورت امکان millisecond هم اضافه کنید 
ممنونم

**Comment by samanzamani** [comment]
@mahramane 
مورد اول اصلاح شد و چون باگ بود با نسخه ۱.۲ منشر میشه
میلی ثانیه هم در دستور کار قرار می دم برای نسخه ۱.۳
ممنون از مشارکتتون

**Comment by VahidGarousi** [comment]
سلام وقتتون بخیر
مقدار 1603744200000رو وقتی به شکل زیر به PersianDate پاس میدم ساعت، دقیقه و ثانیه صفر میشن:

```
  val close = candleItem.close ?: throw IllegalArgumentException("")
  val timestamp = candleItem.time ?: throw IllegalArgumentException("")
PersianDate(timestamp)
```
![Screenshot 2022-09-22 093729](https://user-images.githubusercontent.com/19606714/191671052-b0509af9-01f9-45b5-831f-b85d0e8da242.jpg)

![Screenshot 2022-09-22 093117](https://user-images.githubusercontent.com/19606714/191671002-c436059e-e16a-41fe-8c16-deba27fb5e79.jpg)
