### ISSUE TITLE
مشکل در اضافه کردن  شماره ماه به شهریورماه

### ISSUE THREAD

**Issue by ourbuziness** [samanzamani/PersianDate#57]
وقتی تاریخ فعلی به صورت ۱ شهریور ماه هست و با دستور 
`addMonth`
یک واحد به ماه تاریخ اضافه میکنیم تاریخ جدید ۳۱ شهریور ماه میشود .
در مورد سایر ماه ها این مشکل وجود ندارد

**Comment by samanzamani** [comment]
این مشکل مرتبط با باگ گزارش شده در #54 بود که با اپدیت ۱.۲ حل میشه
ممنون از مشارکتتون و گزارش خطایی که دادید.
