### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by shahinesi** [samanzamani/PersianDate#6]
Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.samanzamani.persiandate:PersianDate:0.2.
Open File
Show Details

Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.github.samanzamani.persiandate:PersianDate:0.2.
Open File
Show Details

Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.github.samanzamani.persiandate:PersianDate:0.2.
Open File
Show Details

Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve com.github.samanzamani.persiandate:PersianDate:0.2.
Open File
Show Details

Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve com.github.samanzamani.persiandate:PersianDate:0.2.
Open File
Show Details

**Comment by samanzamani** [comment]
You may be trying to download this library with Iran IP. ‌Bintray suspends Iran IP. use VPN or something else to change your IP.
