### ISSUE TITLE
Week

### ISSUE THREAD

**Issue by SudoDios** [samanzamani/PersianDate#61]
Hi.
How to get first week day of month
For example, **the first day of the month is Tuesday**

**Comment by SudoDios** [comment]
i using **getDayOfWeek** but is wrong start weekday of month.

**Comment by samanzamani** [comment]
Hi @SudoDios 
You can initiate `PersianDate` with desire `Jalali` date and after that use `dayName` method to get the day name in Farsi.
```java
PersianDate pDate = new PersianDate().initJalaliDate(1400,10,1);
pDate.dayName();//It returns `چهارشنبه`
```

**Comment by SudoDios** [comment]
No no.
I did not mean to name the day.
I want to get the first day of the week in the month (what day does the moon start)

**Comment by SudoDios** [comment]
Do you really have a library for Hijri Date?

**Comment by SudoDios** [comment]
I resolved 

> No no. I did not mean to name the day. I want to get the first day of the week in the month (what day does the moon start)

I solved my problem.
Thankful
