### ISSUE TITLE
persian date for compose desktop

### ISSUE THREAD

**Issue by momeni1367** [samanzamani/PersianDate#63]
سلام ممنون از زحماتتون ... من از این کتابخونه  تو android compose استفاده کردم خیلی خوبه ... این کتابخونه برا compose desktop نمیشه استفاده کرد ؟ خطا میده  ... راه حلی دارید ؟

**Comment by samanzamani** [comment]
سلام
هسته اصلی و تمام امکانات این کتابخانه در دو فایل [PersianDate.java](https://github.com/samanzamani/PersianDate/blob/master/persiandate/src/main/java/saman/zamani/persiandate/PersianDate.java) و [PersianDateFormat.java](https://github.com/samanzamani/PersianDate/blob/master/persiandate/src/main/java/saman/zamani/persiandate/PersianDateFormat.java) پیاده سازی شده که می تونید این دوتا فایل رو به صورت مستقیم در پروژه‌تون اضافه و ازش استفاده کنید.
دقت کنید برای اطلاع از اپدیت های بعدی کتابخانه پروژه رو Watch کنید.

**Comment by momeni1367** [comment]
حل شد . ممنون
