### ISSUE TITLE
English Support for Month & Weekday Names

### ISSUE THREAD

**Issue by yasandev** [samanzamani/PersianDate#65]
Currently, we can only get the date strings in Persian but in some scenarios, it's better to show the Persian date in English characters. It would be really useful to have the option to get the date in English instead of Persian.

**Comment by samanzamani** [comment]
Hi @yasandev 
Farsi characters were added in v1.3.3 and you can choose between Farsi or English characters when you use `PersianDateFormater` class.

https://github.com/samanzamani/PersianDate/issues/46

**Comment by yasandev** [comment]
I want pretty much the opposite of that. I want to format my Persian dates into strings like these:
*Shanbe 1 Khordad* and *Saturday 1 Khordad*.

These can be useful for projects where Persian Date should be supported but the app wants to respect the device's language; showing Persian Date but in English.

It looks like #66 adds what I am requesting except for being able to show weekdays in English.

**Comment by samanzamani** [comment]
I see.
I didn't think it was a practical feature. Since @ftml71 already implemented this feature I will check her contribution then merge the pull request and distribute a new version.

**Comment by samanzamani** [comment]
Pull request merged and a new version was released.
This feature is available from v1.5.1.
