### ISSUE TITLE
مشکل تابع initJalaliDate

### ISSUE THREAD

**Issue by mahramane** [samanzamani/PersianDate#68]
سلام تابع initJalaliDate مشکل داره
مثلا تاریخ 
initJalaliDate(1401, 4, 1, 0, 0, 0)

رو تنظیم میکنی توش بعد همونو میگیری 3 تیر رو بر میگردونه در حالی که من 1 تیر زدم.
لطفا بررسی کنید ممنونم.

**Comment by samanzamani** [comment]
سلام
ممنون از گزارش تون
بررسی می کنم

**Comment by mahramane** [comment]
یه مشکل دیگه
dayOfWeek()
اشتباه میگه مثلا امروز که پنجشنبه هست باید 6 برگردونه ولی مینویسه 5
خواهشا اینارو درست کنید کارم گیره ممنونم

**Comment by mahramane** [comment]
تابع subDays  و بقیه تابع های sub  به صورت int ورودی میگیرن اما addDay و بقیه تابع های add به صورت long

**Comment by samanzamani** [comment]
سلام @mahramane 
در مورد تابع ‍‍`initJalaliDate ` من تابع رو تست کردم و نتیجه درست رو داد لطفا اول کتابخانه رو به آخرین نسخه بروز کن و بعد کد زیر اجرا کن ببین چه نتیجه‌ای می گیری.
‍‍‍‍‍```java
    PersianDate pDate = new PersianDate();
    pDate.initJalaliDate(1401, 4, 1, 0, 0, 0);
    Log.i("PersianDate", pDate.toString());//چهارشنبه 1 تیر 1401 
```
نتیجه ای که به من داد ‍‍`چهارشنبه 1 تیر 1401` بود.

تابع `dayofWeek` همون طور که در [مستندات](https://github.com/samanzamani/PersianDate#persiandate) ذکر شده از صفر شروع میشه. یعنی شنبه صفر میشه و جمعه ۶. بازه تغییراتش بین ۰ تا ۶ هست و تابع به درستی کار می کنه.

در مورد `int` بودن پارامترهای ورودی همون طور که به درستی اشاره کردی ورودی ها `long` تنظیم شده بود که در[ کامیت  آخر](https://github.com/samanzamani/PersianDate/commit/9907642ef28181ddc36556746f6bbfce4d37c7f3) اصلاح شد.

لطفا موارد بررسی کن اگر ابهامی نبود بگو تا نسخه جدیدی منتشر کنم.

باتشکر از وقتی گذاشتی و برای بهبود این کتابخانه مشکلات گزارش دادی.

**Comment by mahramane** [comment]
بله درسته
ممنون بابت پیگیریتون زنده باشید
