### ISSUE TITLE
'g' formatter value is is formatted to the same String as `H`

### ISSUE THREAD

**Issue by yasandev** [samanzamani/PersianDate#71]
کد H و g هردو ساعت رو به صورت ۲۴ ساعته نشون میدند درحالی که g باید همیشه ۱۲ ساعته باشه.

با بررسی کد های ‍`PersianDateFormat` بنظر این دو همیشه به یک عدد تبدیل میشند و داخل فرمتر کدی که تبدیلشون میکنه کاملا یکی هست درحالی که باید متفاوت باشه.

**Comment by samanzamani** [comment]
سلام
ممنون از گزارشی که دادید
حتما چکش می کنم

**Comment by samanzamani** [comment]
سلام @yasandev 
همون طور که به درستی اشاره کرده بودی کلمات ‍‍`H` و `g` عملکرد یکسانی در کلاس `PersianDateFormat` داشتند که در نسخه `1.5.4` اصلاح شد.
لطفا کتابخانه رو به آخرین نسخه بروزرسانی کن و مجدد اگر مشکلی بود بررسی کن.
با تشکر از وقتی که گذاشتی و برای بهبود این کتابخانه
