### ISSUE TITLE
مشکل ساعت دقیقه و ثانیه

### ISSUE THREAD

**Issue by VahidGarousi** [samanzamani/PersianDate#73]
سلام وقتتون بخیر
مقدار 1603744200000رو وقتی به شکل زیر به PersianDate پاس میدم ساعت، دقیقه و ثانیه صفر میشن:

```
  val close = candleItem.close ?: throw IllegalArgumentException("")
  val timestamp = candleItem.time ?: throw IllegalArgumentException("")
PersianDate(timestamp)
```
![Screenshot 2022-09-22 093729](https://user-images.githubusercontent.com/19606714/191671052-b0509af9-01f9-45b5-831f-b85d0e8da242.jpg)

![Screenshot 2022-09-22 093117](https://user-images.githubusercontent.com/19606714/191671002-c436059e-e16a-41fe-8c16-deba27fb5e79.jpg)

_Originally posted by @VahidGarousi in https://github.com/samanzamani/PersianDate/issues/54#issuecomment-1254571506_

**Comment by samanzamani** [comment]
سلام @VahidGarousi 
ممنون از گزارشتون من کد شما رو بررسی کردم و مشکلی در کتابخانه وجود ندارد. زمان timestamps که شما استفاده کردید یعنی 1603744200000 دقیقا برای روز ۰۶ آبان ۱۳۹۹ ساعت ۰۰:۰۰:۰۰ نیمه شب هست. برای همین کتابخانه ساعت و دقیقه و ثانیه رو صفر میده. به عنوان نمونه شما می تونید به همین timestamps مقدار 3600000 میلی ثانیه اضافه کنی تا ساعت ۱ بعد از نیم شب بهت بر میگردونه:

```java
PersianDate pDate = new PersianDate(1603747800000L);
Log.i("PersianDate",pDate.toString());//سه‌شنبه 6 آبان 1399 01:00:00
```

باز هم اگر سوال یا ابهامی داشتی بگو تا بیشتر توضیح بدم.
