### ISSUE TITLE
دریافت تاریخ یک ماه مشخص یا سال

### ISSUE THREAD

**Issue by Rahim-Mahmoudzadeh** [samanzamani/PersianDate#74]
سلام و وقت بخیر خدمت شما 
از کتابخانه ای که ساخت اید خیلی ممنونم 
فقط می خواستم با کمک این کتابخانه روز های یک ماه و یا یک سال را استخراج بکنم
به عنوان مثال برای دریافت روز های ماه ابان 1401 که 1 این ماه از یکشنبه شروع می شود و تا 30 ام روز دوشنبه که پایان این ماه هست چطور می توانم این کار را هندل بکنم 
خیلی ممنونم

**Comment by samanzamani** [comment]
سلام
در حال حاضر متد مستقیم برای این کار نیست و باید ا زمتد `dayOfWeek`  استفاده کنید. این متد برای شنبه عدد صفر و به ترتیب سایر روزها بین ۰-۶ یک عدد را بر می گرداند.
مثال بررسی اولین روز ماه آبان سال ۱۴۰۲:

```java
    PersianDate persianDate = new PersianDate().initJalaliDate(1402,8,1);
    Log.i("PersianDate","First day int is:" + persianDate.dayOfWeek());//return 2 which means Monday
```
