### ISSUE TITLE
چک کردن امروز است

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [samanzamani/PersianDate#75]
سلام وقت شما بخیر
از کتابخانه ای که ساخت اید خیلی ممنونم
لطفا تابع چک کردن آیا این تاریخ امروز است به کلاس PersianDate اضافه کنید (مثل این تابع DateUtils.isToday ) 
با تشکر

**Comment by samanzamani** [comment]
سلام
ممنون از پیشنهادتون 
توی نسخه جدید اضافه خواهد شد.

**Comment by samanzamani** [comment]
سلام @AlirezaGhanbarinia 
متد `isToday` در نسخه `1.6.0` اضافه شد.
با تشکر از پیشنهادی که در مسیر بهبود این کتابخانه داده بودید.
