### ISSUE TITLE
تبدیل به String و برعکس

### ISSUE THREAD

**Issue by Borderliner** [samanzamani/PersianDate#76]
با سلام و خسته نباشید.
میدونم که برای تبدیل تاریخ به متن میشه از `PersianDate().toString()` استفاده کرد. حالا برعکس اگه بخوایم یه تاریخی که به صورت متن هستش رو ازش یه آبجکت PersianDate بسازیم. مثلا:
```
val dateString = PersianDate().toString()
val date = PersianDate.fromString(dateString) // برای مثال
```
این رو نیاز دارم چون باید تاریخ رو توی کلاسی که Parcelable هست استفاده کنم. خیلی ممنون.

**Comment by samanzamani** [comment]
سلام
برای تبدیل تاریخ از `string` به `PersianDate` می تونید از کلاس `PersianDateFormat` و متد `parse` استفاده کنید.
مثال:
```java
String sampleDate1 = '1401-10-10';
String sampleDate2 = '1401-10-13 22:10:15';
PersianDateFormat formater = new PersianDateFormat();
try{
  PersianDate pDate1 = formater.parse(sampleDate1,'yyyy-MM-dd');
  PersianDate pDate2 = formater.parse(sampleDate1,'yyyy-MM-dd HH:mm:ss');
}catch(){}
```

اطلاعات بیشتر در [مستندات](https://github.com/samanzamani/PersianDate#persiandateformat) وجود داره.

**Comment by Borderliner** [comment]
اگه pattern اش رو ندونم چی؟ یعنی یه آبجکتی که با initJalali ساختم.

**Comment by Borderliner** [comment]
متوجه شدم خیلی ممنونم. ولی کاش یه راه حل یک خطی هم داشت. من از کاتلین استفاده میکنم، دوست ندارم هربار که آبجکت میسازم دو سه خط کد بنویسم. البته خودم میتونم حلش کنم ولی کاش این قابلیت وجود داشت.
