### ISSUE TITLE
تبدیل ساعت میلادی به شمسی

### ISSUE THREAD

**Issue by mohsenmdb** [samanzamani/PersianDate#78]
سلام ممنون بابت زحماتتون
مشکل اینه که تاریخ رو به صورت میلادی از سرور دریافت میکنم و وقتی پارسش میکنم ساعت تغییر نمیکنه
مثلا من این تاریخ را دریافت میکنم
 2023-01-10T08:25:03.070504
و برای پارس کردنش این کد رو دارم 
`val date = PersianDateFormat("yyyy-MM-dd'T'HH:mm:ss").parseGrg(time)`
و برای نمایش تاریخ شمسی به این صورت خروجی میگیرم
`"${date.shYear}/${date.shMonth}/${date.shDay} - ${date.hour}:${date.minute}"`
ساعت به جای ۱۱:۵۵ همون ۸:۲۵ دقیقه نمایش داده میشد
لطفا راهنمایی کند که چطور ساعت رو هم به تایم ایران تبدیل کنم
ممنون

**Comment by samanzamani** [comment]
سلام
وقتی دیتا رو تبدیل می کنید تایم زون در نظر نمی گیره.
دوتا راه دارید:
۱-تایم زون رو توی سرور‌تون تنظیم کنید
۲-با توجه به اینکه تایم زون سرور ثابته اختلاف زمان رو به ساعت به تاریخ تبدیل شده با متد‌های `addHours` و `addMinutes` اضافه کنید

**Comment by mohsenmdb** [comment]
سلام ممنون از پاسخی که دادین
من متد‌های addHours و addMinutes رو پیدا نکردم روی نسخه 1.5.4 ولی با متد زیر مسالم حل شد
            `date.addDate(0,0,0,3,30,0)`
فقط مساله که میمونه اینه که بهار که ساعت ها رو میکشن جلو باز هم کد من ساعت صحیح رو نمایش میده؟
یا باید یه شرط بزارم که اگه شش ماه اول سال بود یه تایمی اضافه بشه و اگه شش ماه دوم بود یه تایم دیگه؟
بازم ممنون از راهنماییتون

**Comment by samanzamani** [comment]
سلام
بستگی داره سرور اصلی تون توی کدوم کشور میزبانی بشه.
