### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by Mahdiazadbar** [samanzamani/PersianDate#8]
i used this code.
       PersianDate persianDate = new PersianDate(System.currentTimeMillis());
        PersianDateFormat format = new PersianDateFormat("y/m/d-H:i:s");
       String time=format.format(persianDate);

but time show me +4:30. how can i correct it?

**Comment by samanzamani** [comment]
No need use `System.currenTimeMillis` for get current time.
The date and time are set according to the device's clock. check device clock.

```java
PersianDate persianDate = new PersianDate();
PersianDateFormat format = new PersianDateFormat("y/m/d-H:i:s");
String time=format.format(persianDate);
```

**Comment by Mahdiazadbar** [comment]
Right.
But this is a example. see this scenario. i save current date in Database in other activity. and in other time retrieve this this  date but its incorrect.

**Comment by samanzamani** [comment]
Just send timestamp from other activity or get from database for `init` PersianDate object
