### ISSUE TITLE
مشکل در تبدیل تایم استمپ به تاریخ شمسی

### ISSUE THREAD

**Issue by mehdir32** [samanzamani/PersianDate#9]
سلام
 من دارم با تابع  زیر تایم استمپ رو تبدیل میکنم اما برای تمامی تاریخ ها سال 1348 رو میزاره و کلا تبدیلش اشتباه هست
created = 1531642386;
tv_date.setText(new PersianDate((long) created)+"");

خروجی : یکشنبه 28 دی 1348 21:02:15

**Comment by samanzamani** [comment]
سلام
زمان میلی ثانیه باید باشه
سه تا صفر به اخر تاریخ اضافه کنید

**Comment by mehdir32** [comment]
ممنونم اما با اضاف کردن سه تا فر هم درست نشد و هیچ تغییری نکرد

**Comment by samanzamani** [comment]
من این دوتا کد تست کردم
`
Log.i("TAG",PersianDateFormat.format(new PersianDate(1531642386),null))
`
خروجی
`یکشنبه 28 دی 1348 21:02:15`


بعد از اضافه کردن سه تا صفر:
`
Log.i("TAG",PersianDateFormat.format(new PersianDate(1531642386000),null))
`
خروجی

`یک‌شنبه 24 تیر 1397 12:43:06`

**Comment by mehdir32** [comment]
ممنون درست شد
